# action.yml
name: app-state-diagram
description: Produces a full application state diagram and hyperlinked documentation from ALPS profile
branding:
  icon: 'anchor'
  color: 'blue'
inputs:
  config:
    description: Config file
    required: false
  profile:
    description: Profile file
    required: false
    default: profile.xml
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.config }}
    - ${{ inputs.profile }}
